FROM python:3.6
LABEL mantainer 'alineakaki1@gmail.com'

ENV PYTHONUNBUFFERED 1 
RUN pip install  --proxy http://aakaki:%40lineakak195@proxy.boavistaservicos.com.br:8080 redis==2.10.5 

ENTRYPOINT ["/usr/local/bin/python"]